# Generated by Django 4.2.1 on 2023-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verify',
            field=models.BooleanField(default=False, verbose_name='Проверка адреса почты'),
        ),
    ]
