# Generated by Django 4.2.1 on 2023-06-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
