# Generated by Django 4.2.1 on 2023-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verify',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Подтверждение почты'),
        ),
    ]
