# Generated by Django 4.2.1 on 2023-06-22 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_alter_version_is_current_alter_version_version_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_to_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
