# Generated by Django 4.2.1 on 2023-06-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_link_to_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link_to_owner',
            new_name='product_owner',
        ),
    ]
